"""
Retrieval agent for the AEC pipeline.

The retrieval agent is responsible for providing a set of exemplar
sentences that illustrate how the target event might be realised in
natural language.  In the original AEC framework these exemplars are
generated by prompting a large language model with an event
definition.  In this implementation we support two simple strategies:

1. ``example_db`` – a user‑supplied mapping from event type names
   to lists of exemplar sentences.  When present the agent selects
   examples from this dictionary.
2. ``fallback`` – if no user examples are available the agent returns
   a synthetic exemplar generated from the schema itself.  The
   synthetic exemplar takes the form of a plain English prompt
   describing the event type and its roles.

The returned exemplars are intended to help the planning agent
disambiguate triggers and understand what kind of information to
extract for each role.  They are not used directly in scoring.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from .event_schema import EventSchema


@dataclass
class RetrievalAgent:
    """A simple retrieval agent.

    Parameters
    ----------
    example_db : Dict[str, List[str]], optional
        A mapping from event type names to lists of exemplar
        sentences.  If provided and a key matching the event type
        exists, the agent will draw examples from this dictionary.
    """

    example_db: Optional[Dict[str, List[str]]] = None

    def retrieve(self, schema: EventSchema, k: int = 3) -> List[str]:
        """Return up to ``k`` exemplar sentences for the given schema.

        If an ``example_db`` was provided and contains entries for
        ``schema.event_type`` then those examples are returned (up to
        ``k`` items).  Otherwise a synthetic exemplar describing the
        event is generated.
        """
        if self.example_db and schema.event_type in self.example_db:
            examples = self.example_db[schema.event_type][:k]
            return examples
        # fallback: generate a synthetic exemplar based on the roles
        role_desc = ", ".join(f"{role} ({typ.__name__})" for role, typ in schema.roles.items())
        synthetic = (
            f"An instance of the '{schema.event_type}' event is characterised by the trigger word(s) "
            f"and includes the following arguments: {role_desc}.\n"
            f"Provide a sentence that clearly mentions the trigger and all arguments."
        )
        return [synthetic]